### ISSUE TITLE
Make it work on Node.js

### ISSUE THREAD

**Issue by jpotts18** [isaacsloan/petergate#1]
:+1:

**Comment by isaacsloan** [comment]
At this time that would require a complete rewrite so it's not currently a priority. If you'd like to look into that I'll except pull requests. :)

**Comment by jpotts18** [comment]
I'd like to see a video that shows how to use it. Like a screen cast or something. If you are willing to help me get it working I'd be happy to right down some docs and/or make a screen cast.
