### ISSUE TITLE
User with multiple roles can't access anything restricted to second or third.. roles

### ISSUE THREAD

**Issue by JoshJuncker** [isaacsloan/petergate#10]
Access to a controller by a user with multiple roles doesn't work.  Ex. a user has the role of :user and :admin.  They can access :user restricted controllers, but they can't access :admin restricted controllers.

**Comment by isaacsloan** [comment]
This will work now. if you could add another crud controller and tests into the dummy application in the gem that would be amazing. Split the roles between two roles and make sure that a user with both roles can do everything.
