### ISSUE TITLE
Failure when setting roles

### ISSUE THREAD

**Issue by JoshJuncker** [isaacsloan/petergate#9]
See below for an example.  The following might work for setting roles.
def roles=(v)
    self[:roles] = v.map(&:to_sym).to_a.select{|r| ROLES.include?(r)}
end

2.2.2 :005 > u = User.second
  User Load (0.4ms)  SELECT  `users`.* FROM `users`  ORDER BY `users`.`id` ASC LIMIT 1 OFFSET 1
 => #<User id: 2, email: "user@example.com", encrypted_password: "$2a$10$HHaM8URgTWy2AAVOGQ63Y.a8nB93Hot7./5yQejW/6Q...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, first_name: "Test", last_name: "User", phone_number: nil, created_at: "2015-08-18 19:43:23", updated_at: "2015-08-18 19:43:23", recurly_account_id: nil, recurly_account_state: nil, recurly_card_last_four: nil, subscription_aasm_state: "invalid", roles: [:user]> 
2.2.2 :006 > u.roles = [:super_admin]
NoMethodError: undefined method `size' for :super_admin:Symbol
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/petergate-1.2.0/lib/petergate/active_record/base.rb:33:in `block in roles='
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/petergate-1.2.0/lib/petergate/active_record/base.rb:33:in `select'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/petergate-1.2.0/lib/petergate/active_record/base.rb:33:in `roles='
	from (irb):6
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
2.2.2 :007 > u.roles = [:user, :super_admin]
NoMethodError: undefined method `size' for :user:Symbol
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/petergate-1.2.0/lib/petergate/active_record/base.rb:33:in `block in roles='
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/petergate-1.2.0/lib/petergate/active_record/base.rb:33:in `select'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/petergate-1.2.0/lib/petergate/active_record/base.rb:33:in `roles='
	from (irb):7
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/junckdawg/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by isaacsloan** [comment]
This issue is wack! I can't reproduce it.

**Comment by isaacsloan** [comment]
Try running
    :testing.size 
in your console.

**Comment by isaacsloan** [comment]
http://glui.me/?i=iaq439e4pnmmt0d/2015-08-21_at_12.11_AM.png/

**Comment by JoshJuncker** [comment]
Found a fix.  I removed gem 'mongoid', '~> 4.0.0' from my gemfile, bundled, and then it worked.  Then I added mongoid back the exact same and bundled and it worked.  Something must have been messed up with the mongoid gem installation.
